#pragma once

#include "modem/xe310.h"

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#define MAX_SERVER_CONNECTIONS 5

namespace modem {

/// States of the LTE network state machine.
enum class NetworkLteState : uint8_t {
    none,
    switched_off,
    off_mode,
    sleep_mode,
    setup_mode,
    idle_mode,
    network_detached,
    network_attaching,
    pdp_context_closed,
    pdp_context_opening,
    data_ready,
    transparent_mode,
    modem_fota,
    done,
};

/// Events that drive state transitions.
enum class NetworkLteEvent : uint8_t {
    none,
    // External / user events
    wake_up,                // wake up from sleep mode (PSM)
    send_data,              // trigger data send flow (if in data ready state) or buffer data to send when we get to data ready state
    transparent_mode,       // trigger transparent mode flow (if supported by modem)
    data_complete,          // triggered when we receive a solicitation from user that data transfer is complete and we can go back to idle or sleep mode, depending on the configuration
    // power events
    power_on,               // power on modem completely (e.g. by supplying power)
    power_off,              // power off modem completely (e.g. by cutting power or shutting down)
    turn_on_radio,          // turn on modem radio
    switch_off_radio,       // switch off modem radio
    enter_sleep,            // enter sleep mode (PSM)
    setup_radio,            // setup modem radio
    // modem urc events
    psm_enter,              // +CPSMS URC indicates PSM entry
    psm_exit,               // +CPSMS URC indicates PSM exit
    network_detached,       // e.g. +CEREG deregistration URC
    network_attached,       // e.g. +CEREG registration URC
    context_opened,         // e.g. +CGACT || +CGEV activation URC
    context_closed,         // e.g. +CGACT || +CGEV deactivation URC
    context_rejected,       // e.g. +CGACT || +CGEV activation rejected URC
    data_available,         // incoming data URC (e.g. SRING)
    // Routing events (generated by step() in idle_mode)
    query_network_status,   // triggered in idle mode to check if we are already registered to network or not, and decide whether to start attach flow or not
    query_network_context,  // triggered in idle mode after network attach to check if we already have an active PDP context or not, and decide whether to start PDP activation flow or not
    // Action completion events (generated by step())
    attach_started,         // triggered after we send the command to start attach flow
    pdp_opening,            // triggered after we send the command to start PDP activation flow
    // Asynchronous modem / server events
    timeout,                // triggered when we time out waiting for an expected event (e.g. attach completion, PDP activation, server connection, data transfer)
    // errors
    network_error,          // generic error for network-related failures (e.g. registration failure, unexpected detach, etc.) that can trigger retries and fallback mechanisms before giving up and going to done state
    attach_error,           // specific error for attach failures (e.g. after max attach retries reached)
    context_error           // specific error for PDP context activation failures (e.g. after max PDP activation retries reached)
};

/// Configuration for the LTE network state machine.
struct NetworkLteConfig {
    uint8_t     cid                      = 1; ///< PDP context ID to use for LTE data connection (default 1, must be >0)
    uint8_t     attach_timeout_sec       = 60; ///< Timeout for network attach in seconds
    uint8_t     pdp_timeout_sec          = 30; ///< Timeout for PDP context
    uint8_t     max_network_attempts     = 2; ///< Timeout for server connection and data transfer
    uint8_t     max_attach_retries       = 2;
    uint8_t     max_pdp_retries          = 2;

    uint64_t    default_lte_bands        = 524420;
    uint8_t     default_iot_tech         = 0;
    std::string default_apn              = "internet";

    uint64_t    fallback_lte_bands       = 524420;
    uint8_t     fallback_iot_tech        = 1;
    std::string fallback_apn             = "internet";

    std::string plmn                     = ""; ///< Optional PLMN to attach to (e.g. "310260" for T-Mobile US). If empty, modem default will be used.

    uint8_t     conn_id                  = 0; ///< Connection ID to query for server connection status (e.g. for UDP sockets)    
    std::string gw_server_address        = "example.com";
    uint16_t    server_port              = 1234;
    std::string bootstrap_server_address = "example.com";
    uint16_t    bootstrap_server_port    = 1234;
    std::string fota_server_address      = "example.com";
    uint16_t    fota_server_port         = 1234;
    
};

enum class ServerState : uint8_t {
    unknown,
    disconnected,
    connected,
};

struct ServerInfo {
    uint8_t conn_id;
    ServerState state = ServerState::disconnected;
    std::string protocol;
    std::string address;
    uint16_t port;
};


/// LTE network state machine — drives modem attach, PDP activation and server registration.
class NetworkLte {
public:
    using DataReceivedCallback = std::function<void(uint8_t cid, std::string& data, uint16_t n_bytes)>;

    explicit NetworkLte(xE310& modem, const NetworkLteConfig& config = {},
                        DataReceivedCallback on_data_received = nullptr);

    NetworkLteState state() const;
    NetworkLteEvent event() const;
    uint8_t get_network_attempts() const;        // returns nNetworkAttempts (for testing)
    void    set_network_attempts(uint8_t n);     // sets nNetworkAttempts (for testing)
    uint8_t get_attach_retries() const;          // returns nAttachRetries (for testing)
    uint8_t get_pdp_retries() const;    // returns nPdpRetries (for testing)
    void set_attach_retries(uint8_t n); // sets nAttachRetries (for testing)
    void set_pdp_retries(uint8_t n);   // sets nPdpRetries (for testing)

    /// Execute one step of the state machine: processes the current event
    /// and performs the modem action for the current state.
    NetworkLteState loop(NetworkLteState target_state = NetworkLteState::none);
    
    /// Configure a new server connection with the given parameters. Does not trigger any state changes by itself.
    void new_connection(uint8_t conn_id, const std::string& protocol, const std::string& ip, const std::string& port);
    /// Connect to the network and server using the current configuration. Blocks until connected or max retries reached.
    bool server_connect(uint8_t conn_id, const std::string& protocol, const std::string& ip, const uint16_t port);
    /// Disconnect from the network and server. Blocks until disconnected.
    bool server_disconnect(uint8_t conn_id);
    /// Send data to the server. Data is buffered if not currently connected.
    bool send_data(uint8_t cid, uint8_t* data, size_t length);
    /// Enter sleep mode (PSM).
    bool enter_sleep();
    /// Enter transparent mode (if supported by the modem).
    bool enter_transparent_mode();
    /// Exit transparent mode (go to idle state).
    bool exit_transparent_mode();
    /// @brief Send an AT command to the modem and receive the response.
    /// @param command The AT command to send.
    /// @param response The response from the modem.
    /// @param timeout_ms The timeout for the AT command in milliseconds.
    /// @return True if the command was successful, false otherwise.
    bool send_at_command(std::string command, std::string& response, uint16_t timeout_ms);
    /// @brief Update the modem firmware or configuration.
    /// @return True if the update was successful, false otherwise.
    bool update_modem(std::string firmware_url);

    // --- Cached modem state accessors ---

    /// Last registration info read from the modem.
    const RegistrationInfo& registration_info() const;

    /// Last signal quality read from the modem.
    const SignalQuality& signal_quality() const;

    /// SIM ICCID read at power-on.
    const std::string& iccid() const;

    /// SIM IMSI read at power-on.
    const std::string& imsi() const;

    /// Active configuration.
    const NetworkLteConfig& config() const;

    /// Replace the active configuration (takes effect on the next step cycle).
    void set_config(const NetworkLteConfig& config);

    // !! private functions but set as public for testing purposes, since we want to be able to call them directly from unit tests to test specific state transitions and flows without having to go through the whole state machine loop and trigger the corresponding events
    
    // callback to retrieve data received from the modem (e.g. from +RECEIVE URC) and pass it to the user-provided callback for processing
    DataReceivedCallback on_data_received_;
    
    // Triggered by modem events (e.g. URCs) to update the current event and drive state transitions.
    void on_modem_event(NetworkLteEvent event);

    // Set the current event to trigger a state transition on the next step() call.
    void on_event(NetworkLteEvent event);

    // Change to a new state immediately, bypassing the normal event-driven flow (for testing).
    void change_state(NetworkLteState new_state);
    
    // Force a transition to the given state by generating the necessary sequence of events and calling loop() until the target state is reached.
    bool go_to_state(NetworkLteState target_state);

    // Iterate once state machine with the given event (for testing).
    void step();

    /// Log current state and event using MODEM_LOG_DBG.
    void log_state() const;
    
    /// Log current event using MODEM_LOG_DBG.
    void log_event() const;

    /// Process a single URC line (e.g. "+CREG: 1") and update event_ if relevant.
    void handle_urc(const std::string& urc);
private:
    xE310& modem_;
    ModemInfo            modemInfo;
    SimStatus            simStatus           = SimStatus::not_inserted;
    RadioTech            radioTech           = RadioTech::lte;
    RegStatus            regStatus           = RegStatus::not_registered;
    RegistrationInfo     regInfo;
    NetworkInfo          networkInfo;
    SignalQuality        signalQuality;
    PsmMode              psmMode             = PsmMode::disable;
    CpsmsConfig          cpsmsConfig;
    TelitCpsmsConfig     telitCpsmsConfig;
    TelitCpsmsStatus     telitCpsmsStatus;
    NetworkSurveyResult  networkSurveyResult;
    ServerInfo           serverInfo[MAX_SERVER_CONNECTIONS];

    NetworkLteConfig lteConfig;
    NetworkLteState state_ = NetworkLteState::switched_off;
    NetworkLteState prev_state_ = NetworkLteState::none;
    NetworkLteEvent modem_event_ = NetworkLteEvent::none;
    NetworkLteEvent event_ = NetworkLteEvent::none;
    uint8_t nNetworkAttempts = 0; // number of consecutive network attempts (attach + PDP activation)
    uint8_t nAttachRetries = 0; // number of consecutive attach attempts
    uint8_t nPdpRetries = 0; // number of consecutive PDP activation attempts

    bool fFirstTimeBoot = true;  ///< Whether the modem has completed its first boot sequence since power-on.
    bool fNewConfig = true;      ///< Whether the modem configuration has been changed and not yet applied.
};

} // namespace modem
