#pragma once

#include "modem/i_radio_lte.h"
#include "modem/message_queue_factory.h"
#include "modem/timer_factory.h"
#include "modem/xe310.h"
#include "modem_controller.h"
#include "xe310.h"

#include <cstdint>
#include <array>
#include <functional>
#include <memory>
#include <string_view>

#if !defined(PLATFORM_ZEPHYR) && !defined(__ZEPHYR__)
#include <condition_variable>
#include <mutex>
#endif

#define MAX_SERVER_CONNECTIONS 5

namespace modem {

/// States of the LTE network state machine.
enum class NetworkLteState : uint8_t {
    none,
    rebooting,
    switched_off,
    off_mode,
    sleep_mode,
    setup_mode,
    idle_mode,
    network_detached,
    network_attaching,
    pdp_context_closed,
    pdp_context_opening,
    data_ready,
    transparent_mode,
    modem_fota,
    done,
};

/// Events that drive state transitions.
enum class NetworkLteEvent : uint8_t {
    none,

    // modem urc events
    psm_enter,        // triggered by +URC PSM
    psm_exit,         // wake up from sleep mode (PSM), triggered by GPIO Wake0, go to data ready, wait for CTS line
    network_detached, // e.g. +CEREG deregistration URC
    network_attached, // e.g. +CEREG registration URC
    context_opened,   // e.g. +CGACT || +CGEV activation URC
    context_closed,   // e.g. +CGACT || +CGEV deactivation URC
    context_rejected, // e.g. +CGACT || +CGEV activation rejected URC
    data_available,   // incoming data URC (e.g. SRING)

    // internal events (generated by step())
    attach_started, // triggered after we send the command to start attach flow
    pdp_opening,    // triggered after we send the command to start PDP activation flow

    // Asynchronous modem / server events
    timeout, // triggered when we time out waiting for an expected event (e.g. attach completion, PDP activation, server
             // connection, data transfer)

    // errors
    network_error, // generic error for network-related failures (e.g. registration failure, unexpected detach, etc.)
                   // that can trigger retries and fallback mechanisms before giving up and going to done state
    attach_error,  // specific error for attach failures (e.g. after max attach retries reached)
    context_error, // specific error for PDP context activation failures (e.g. after max PDP activation retries reached)
    at_command_no_response, // error for unexpected AT command failures (e.g. modem becomes unresponsive, or returns an
                            // error to a command we expect to always succeed like AT or AT+CGMM). This can trigger
                            // recovery actions like modem reboot or factory reset.
};

/// Actions that the state machine can trigger on the modem. These are executed in loop() based on the current state and
/// event.
enum class ModemAction : uint8_t {
    none,
    // recovering actions
    reboot,
    factory_reset,
    check_responsiveness,
    // power actions
    power_on,         // power on modem completely (e.g. by supplying power)
    power_off,        // power off modem completely (e.g. by cutting power or shutting down)
    turn_on_radio,    // turn on modem radio
    switch_off_radio, // switch off modem radio
    enter_sleep,      // call cfun=4 + cfun=11, monitor POWERMON
    wake_up,          // drive GPIO0 + CFUN=1, Warm boot
    setup_radio,      // setup modem radio
    // internal actions to get current state
    query_network_status, // triggered in idle mode to check if we are already registered to network or not, and decide
                          // whether to start attach flow or not
    query_pdp_context, // triggered in idle mode after network attach to check if we already have an active PDP context
                       // or not, and decide whether to start PDP activation flow or not
    // internal actions to drive state machine forward based on events
    attach_network,   // triggered in network detached state to start attach flow
    open_pdp_context, // triggered in network attached state to start PDP activation flow
    // data actions
    send_data, // trigger data send flow (if in data ready state) or buffer data to send when we get to data ready state
    read_data, // trigger data read flow (if in data ready state)
    data_complete, // triggered when we receive a solicitation from user that data transfer is complete and we can go
                   // back to idle or sleep mode, depending on the configuration
    // special modes
    enter_transparent_mode, // trigger transparent mode flow (if supported by modem)
    leave_transparent_mode, // trigger exit transparent mode flow (if supported by modem)
};

enum class NetworkTraceKind : uint8_t {
    state_change,
    event_set,
    action_set,
    error,
};

struct NetworkTraceEntry {
    NetworkTraceKind kind = NetworkTraceKind::state_change;
    NetworkLteState previous_state = NetworkLteState::none;
    NetworkLteState current_state = NetworkLteState::none;
    NetworkLteEvent event = NetworkLteEvent::none;
    ModemAction action = ModemAction::none;
};

enum class ServerState : int8_t {
    unknown = -1,
    disconnected,
    connected,
    suspended,
    pending_data,
    listening,
    incoming_connection,
    dns_resolving,
    connecting
};

struct ServerInfo {
    uint8_t conn_id = 0;
    ServerState state = ServerState::disconnected;
    FixedString<MODEM_SHORT_STR> protocol;
    FixedString<MODEM_IP_STR> address;
    uint16_t port = 0;
    bool fHasData = false; // flag to indicate if we have data to send to the server, used to trigger data send flow
                           // when we get to data ready state
};

/// LTE network state machine — drives modem attach, PDP activation and server registration.
class NetworkLte : public IRadioDataQueue {
public:
    using DataReceivedCallback = std::function<void(uint8_t cid, std::string_view data, uint16_t n_bytes)>;

    explicit NetworkLte(xE310& modem, const NetworkLteConfig& config = {},
                        DataReceivedCallback on_data_received = nullptr, TimerHandle timer = TimerHandle{});

    NetworkLteState state() const;
    NetworkLteEvent event() const;
    uint8_t get_network_attempts() const; // returns nNetworkAttempts (for testing)
    void set_network_attempts(uint8_t n); // sets nNetworkAttempts (for testing)
    uint8_t get_attach_retries() const;   // returns nAttachRetries (for testing)
    uint8_t get_pdp_retries() const;      // returns nPdpRetries (for testing)
    void set_attach_retries(uint8_t n);   // sets nAttachRetries (for testing)
    void set_pdp_retries(uint8_t n);      // sets nPdpRetries (for testing)

    /// Start the internal timer. Fires on_timer_expired() (-> timeout event) after timeout_ms.
    /// Returns TimerError::already_running if the timer is already active.
    TimerError start_timer(uint32_t timeout_ms);

    /// Stop the internal timer. The timeout event will not fire after this returns.
    /// Returns TimerError::not_running if the timer was not active.
    TimerError stop_timer();

    /// Restart the internal timer with a new timeout, keeping the same callback.
    /// Works whether or not the timer is currently running.
    TimerError reset_timer(uint32_t timeout_ms);

    /// Returns true if the internal timer is currently counting down.
    bool is_timer_running() const;

    /// Returns the number of whole seconds elapsed since the timer was last started or reset.
    /// Returns 0 if the timer has never been started.
    uint32_t timer_elapsed_seconds() const;

    /// Execute one step of the state machine: processes the current event
    /// and performs the modem action for the current state.
    NetworkLteState loop(NetworkLteState target_state = NetworkLteState::none);

    /// register on network
    bool network_connect();
    bool network_disconnect();

    /// Configure a new server connection with the given parameters. Does not trigger any state changes by itself.
    void new_connection(uint8_t conn_id, std::string_view protocol, std::string_view ip, std::string_view port);
    /// Connect to the network and server using the current configuration. Blocks until connected or max retries
    /// reached.
    bool server_connect(uint8_t conn_id, std::string_view protocol, std::string_view ip, uint16_t port);
    /// Disconnect from the network and server. Blocks until disconnected.
    bool server_disconnect(uint8_t conn_id);

    /// Write data into the TX queue for the given connection ID (1-based).
    QueueError tx_write(uint8_t conn_id, const uint8_t* data, size_t length) override;

    /// Read data from the RX queue for the given connection ID (1-based).
    QueueError rx_read(uint8_t conn_id, QueueMessage& msg) override;

    /// Try to register on a network with PSM enabled, by checking the current network registration and PSM
    /// configuration, and iterating through available operators if registration or PSM is not available with the
    /// current one. Returns true if successfully registered on a network with PSM enabled, false otherwise.
    bool force_psm();
    /// Enter sleep mode (PSM).
    bool enter_sleep();
    /// Enter transparent mode (if supported by the modem).
    bool enter_transparent_mode();
    /// Exit transparent mode (go to idle state).
    bool exit_transparent_mode();
    /// Alias for exit_transparent_mode — re-enables URCs and returns to idle.
    bool leave_transparent_mode();
    /// @brief Send an AT command to the modem and receive the response.
    /// @param command The AT command to send.
    /// @param response The response from the modem.
    /// @param timeout_ms The timeout for the AT command in milliseconds.
    /// @return True if the command was successful, false otherwise.
    bool send_at_command(std::string_view command, FixedString<AT_RESPONSE_MAX>& response, uint32_t timeout_ms);
    /// @brief Update the modem firmware or configuration.
    /// @return True if the update was successful, false otherwise.
    bool update_modem(std::string_view firmware_url);

    // --- Cached modem state accessors ---

    /// Last registration info read from the modem.
    const RegistrationInfo& registration_info() const;

    /// Last signal quality read from the modem.
    const SignalQuality& signal_quality() const;

    /// SIM ICCID read at power-on.
    const FixedString<MODEM_SHORT_STR>& iccid() const;

    /// SIM IMSI read at power-on.
    const FixedString<MODEM_SHORT_STR>& imsi() const;

    /// Last modem clock read from AT+CCLK?.
    const FixedString<MODEM_SHORT_STR>& clock() const;
    ModemStatus refresh_clock();

    /// Full modem identification info read at power-on.
    const ModemInfo& modem_info() const;

    /// Last known SIM status.
    SimStatus sim_status() const;

    /// Last known radio access technology.
    RadioTech radio_tech() const;

    /// Last known registration status (from URC or query).
    RegStatus reg_status() const;

    /// Last known network/PDP context info.
    const NetworkInfo& network_info() const;

    /// Last known PSM mode.
    PsmMode psm_mode() const;

    /// Last known 3GPP PSM configuration.
    const CpsmsConfig& cpsms_config() const;

    /// Last known Telit PSM configuration.
    const TelitCpsmsConfig& telit_cpsms_config() const;

    /// Last known Telit PSM network status.
    const TelitCpsmsStatus& telit_cpsms_status() const;

    /// Last network survey result (populated after a survey action).
    const NetworkSurveyResult& network_survey_result() const;

    /// List of operators found by the last AT+COPS=? scan.
    const StaticVector<Operator, xE310::MAX_OPERATORS>& available_operators() const;

    /// Result of the last AT#CSURV scan (populated by scan_networks()).
    const CsurvResult& csurv_result() const;

    /// Run AT#CSURVF=2 + AT#CSURV and store results internally.
    /// Optionally restrict to channels [start_ch, end_ch]; pass 0 for both to scan full band.
    bool scan_networks(uint32_t start_ch = 0, uint32_t end_ch = 0);

    /// Pointer to the internal server info array (MAX_SERVER_CONNECTIONS entries, 0-based).
    const ServerInfo* server_info_array() const;

    /// Active configuration.
    const NetworkLteConfig& config() const;

    /// Replace the active configuration (takes effect on the next step cycle).
    void set_config(const NetworkLteConfig& config);

    /// Pop one trace entry produced by state/event/action transitions.
    /// Returns false if timeout expires with no entry available.
    bool pop_trace(NetworkTraceEntry& entry, uint32_t timeout_ms);

    /// Accumulated time counters for timed states.
    const StateTimers& state_timers() const;

    // !! private functions but set as public for testing purposes, since we want to be able to call them directly from
    // unit tests to test specific state transitions and flows without having to go through the whole state machine loop
    // and trigger the corresponding events

    // callback to retrieve data received from the modem (e.g. from +RECEIVE URC) and pass it to the user-provided
    // callback for processing
    DataReceivedCallback on_data_received_;

    // Set the current event to trigger a state transition on the next step() call.
    void on_event(NetworkLteEvent event);

    // Dequeue the current event and return it. The event is reset to none after being read to avoid processing the same
    // event multiple times.
    NetworkLteEvent get_event();

    // Change to a new state immediately, bypassing the normal event-driven flow (for testing).
    void change_state(NetworkLteState new_state);

    // Set the current action to be executed in the next step() call based on the current state and event.
    void call_action(ModemAction action);

    // Get the current action and reset it to none. The action is reset after being read to avoid executing the same
    // action multiple times.
    ModemAction get_action();

    void execute_actions();

    // Force a transition to the given state by generating the necessary sequence of events and calling loop() until the
    // target state is reached.
    bool go_to_state(NetworkLteState target_state);

    // Iterate once state machine with the given event (for testing).
    void step() { loop(); };

    /// Log current state and event using MODEM_LOG_DBG.
    void log_state();

    /// Log current event using MODEM_LOG_DBG.
    void log_event();

    /// Log current action using MODEM_LOG_DBG.
    void log_action();

    /// Log error events using MODEM_LOG_ERR.
    void log_error(NetworkLteEvent error_event);

    /// Process a single URC line (e.g. "+CREG: 1") and update event_ if relevant.
    void handle_urc(std::string_view urc);

    bool check_status_response(ModemStatus status);

    void push_trace(NetworkTraceKind kind, NetworkLteState previous_state, NetworkLteState current_state,
                    NetworkLteEvent event, ModemAction action);

    static constexpr size_t TRACE_CAPACITY = 10;
    std::array<NetworkTraceEntry, TRACE_CAPACITY> trace_buffer_{};
    size_t trace_head_ = 0;
    size_t trace_count_ = 0;
#if !defined(PLATFORM_ZEPHYR) && !defined(__ZEPHYR__)
    std::mutex trace_mutex_;
    std::condition_variable trace_cv_;
#endif

private:
    xE310& modem_;
    ModemInfo modemInfo;
    SimStatus simStatus = SimStatus::not_inserted;
    RadioTech radioTech = RadioTech::lte;
    RegStatus regStatus = RegStatus::not_registered;
    RegistrationInfo regInfo;
    NetworkInfo networkInfo;
    SignalQuality signalQuality;
    FixedString<MODEM_SHORT_STR> modemClock;
    PsmMode psmMode = PsmMode::disable;
    CpsmsConfig cpsmsConfig;
    TelitCpsmsConfig telitCpsmsConfig;
    TelitCpsmsStatus telitCpsmsStatus;
    NetworkSurveyResult networkSurveyResult;
    StaticVector<Operator, xE310::MAX_OPERATORS> operatorList;
    CsurvResult csurvResult;
    ServerInfo serverInfo[MAX_SERVER_CONNECTIONS];

    NetworkLteConfig lteConfig;
    NetworkLteState state_ = NetworkLteState::switched_off;
    NetworkLteState prev_state_ = NetworkLteState::none;
    NetworkLteEvent modem_event_ = NetworkLteEvent::none;
    NetworkLteEvent event_ = NetworkLteEvent::none;
    ModemAction modem_action_ = ModemAction::none;

    uint8_t nNetworkAttempts = 0; // number of consecutive network attempts (attach + PDP activation)
    uint8_t nAttachRetries = 0;   // number of consecutive attach attempts
    uint8_t nPdpRetries = 0;      // number of consecutive PDP activation attempts

    TimerHandle timer_;
    MessageQueueHandle message_queue_;
    uint8_t last_data_conn_id_ = 0; ///< Connection ID from the most recent SRING URC

    StateTimers stateTimers_; ///< Accumulated time counters for timed states.

    /// Called by the timer when it expires; injects a timeout modem event.
    void on_timer_expired();

    bool fColdBoot = false;    ///< Whether the modem has completed its first boot sequence since power-on, cold boot.
    bool fWarmBoot = true;     ///< Whether the modem has completed a subsequent boot sequence since power-on, warm boot
                               ///< (e.g. after a reset or firmware update).
    bool fNewConfig = false;   ///< Whether the modem configuration has been changed and not yet applied.
    bool fChangeBands = false; ///< Whether to change bands after a failed attach attempt (for testing purposes, since
                               ///< in some networks changing bands can help with attach success)
    bool fChangeRAT = false;   ///< Whether to change RAT after a failed attach attempt (for testing purposes, since in
                               ///< some networks changing RAT can help with attach success)

    TimerHandle st_timer; ///< Timer for state timeouts (e.g. attach, PDP activation, server connection)
};

} // namespace modem
