#pragma once

#include "modem/xe310.h"

#include <cstdint>
#include <string>

namespace modem {

/// States of the LTE network state machine.
enum class NetworkLteState : uint8_t {
    switched_off,
    off_mode,
    sleep_mode,
    setup_mode,
    idle_mode,
    detached,
    attaching,
    context_deactivated,
    opening_pdp_context,
    server_disconnected,
    server_registering,
    server_bootstrap,
    data_ready,
    done,
};

/// Events that drive state transitions.
enum class NetworkLteEvent : uint8_t {
    // External / user events
    none,
    power_on,
    power_off,
    turn_on_radio,
    switch_off_radio,
    enter_sleep,
    setup_radio,
    wake_up,
    send_data,
    psm,

    // Routing events (generated by step() in idle_mode)
    query_network_attached,
    query_network_detached,
    query_network_has_context,
    query_server_connected,
    query_server_deregistered,
    network_error,

    // Action completion events (generated by step())
    attach_started,
    network_attached,
    pdp_opening,
    context_activated,
    server_connect,

    // Asynchronous modem / server events
    network_loss,
    context_loss,
    timeout,
    authenticated,
    rejected,
    bootstrap_complete,
    data_complete,
    timeout_server,

    // errors
    attach_error,
    context_error
};

/// Configuration for the LTE network state machine.
struct NetworkLteConfig {
    uint8_t     cid                 = 1; ///< PDP context ID to use for LTE data connection (default 1, must be >0)
    uint8_t     max_attach_retries  = 2;
    uint8_t     max_pdp_retries     = 2;

    uint64_t    default_lte_bands   = 524420;
    uint8_t     default_iot_tech    = 0;
    std::string default_apn         = "internet";

    uint64_t    fallback_lte_bands  = 524420;
    uint8_t     fallback_iot_tech   = 1;
    std::string fallback_apn        = "internet";

    std::string plmn                = ""; ///< Optional PLMN to attach to (e.g. "310260" for T-Mobile US). If empty, modem default will be used.

    uint8_t     conn_id                  = 0; ///< Connection ID to query for server connection status (e.g. for UDP sockets)    
    std::string gw_server_address        = "example.com";
    uint16_t    server_port              = 1234;
    std::string bootstrap_server_address = "example.com";
    uint16_t    bootstrap_server_port    = 1234;
    std::string fota_server_address      = "example.com";
    uint16_t    fota_server_port         = 1234;
    
};

/// LTE network state machine — drives modem attach, PDP activation and server registration.
class NetworkLte {
public:
    explicit NetworkLte(xE310& modem, const NetworkLteConfig& config = {});

    NetworkLteState state() const;
    NetworkLteEvent event() const;
    uint8_t try_count() const;

    /// Execute one step of the state machine: processes the current event
    /// and performs the modem action for the current state.
    NetworkLteState st_machine();

    // Set the current event to trigger a state transition on the next step() call.
    void on_event(NetworkLteEvent event);

    // Iterate once state machine with the given event (for testing).
    void step();

    /// Log current state and event using MODEM_LOG_DBG.
    void log_state() const;

    // --- Cached modem state accessors ---

    /// Last registration info read from the modem.
    const RegistrationInfo& registration_info() const;

    /// Last signal quality read from the modem.
    const SignalQuality& signal_quality() const;

    /// SIM ICCID read at power-on.
    const std::string& iccid() const;

    /// SIM IMSI read at power-on.
    const std::string& imsi() const;

    /// Active configuration.
    const NetworkLteConfig& config() const;

    /// Replace the active configuration (takes effect on the next step cycle).
    void set_config(const NetworkLteConfig& config);

private:
    xE310& modem_;
    ModemInfo            modemInfo;
    SimStatus            simStatus           = SimStatus::not_inserted;
    RadioTech            radioTech           = RadioTech::lte;
    RegStatus            regStatus           = RegStatus::not_registered;
    RegistrationInfo     regInfo;
    NetworkInfo          networkInfo;
    SignalQuality        signalQuality;
    PsmMode              psmMode             = PsmMode::disable;
    CpsmsConfig          cpsmsConfig;
    TelitCpsmsConfig     telitCpsmsConfig;
    TelitCpsmsStatus     telitCpsmsStatus;
    NetworkSurveyResult  networkSurveyResult;
    ServerInfo           serverInfo;

    NetworkLteConfig lteConfig;
    NetworkLteState state_ = NetworkLteState::switched_off;
    NetworkLteEvent event_ = NetworkLteEvent::power_on;
    uint8_t nAttachRetries = 0;
    uint8_t nPdpRetries = 0;
    uint8_t try_count_ = 0;

    bool fFirstTimeBoot = true;  ///< Whether the modem has completed its first boot sequence since power-on.
    bool fNewConfig = true;      ///< Whether the modem configuration has been changed and not yet applied.
};

} // namespace modem
